Dynamically populate the Environment dropdown
metaplex-foundation/mpl-core-ui pull request #14
Opened 2024-12-22 19:26 UTC by beeman

This PR makes the list of available environments dynamic based on the ones that are configured using the environment variables.

![image](https://github.com/user-attachments/assets/8e2a1f89-ac27-4e28-b6af-a333d1c6e818)

2025-01-30 18:51 UTC, nhanphan requested changes
Thanks for your contributions!

2025-01-30 18:51 UTC, nhanphan commented on providers/Providers.tsx
> +  const endpoint = useMemo(() => envOptions.find(({ env: e }) => e === env)?.endpoint, [env]);
not sure if the app correctly handles `endpoint` being `null`, it should probably be defaulted to something (solana mainnet?) if the `find` does not find anything

2025-01-30 18:51 UTC, nhanphan commented on providers/Providers.tsx
> +  const [env, setEnv] = useState<Env>((queryEnv === 'mainnet' || queryEnv === 'devnet') ? queryEnv : envOptions[0]?.env);
I think you found a bug here (thanks!), the logic should probably be: if the `queryEnv` is valid (i.e. contained within `envOptions`) then set the corresponding env otherwise use the first thing in the env options

I checked on the current site and when navigating to a page via url and env set as a search param, the env for sonic/eclipse is not set properly.

2025-01-30 22:10 UTC, beeman commented
> Thanks for your contributions!

Thanks for reviewing and merging a bunch of them! 

I will address the notes above!

2025-02-02 15:55 UTC, beeman commented
@nhanphan I made some tweaks based on your comments above. I think it's more robust now and should always take the first _defined_ environment. This seems better than using `mainnet` as the default because a dev might choose to not add any mainnet endpoints to their app.

Happy to make any changes though, just lmk!

2025-09-20 09:25 UTC, closed without merging